version: '3.8'

services:
  transformer-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true

  transformer-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true 